### ISSUE TITLE
Confusing crate/workflow option on initial generation

### ISSUE THREAD

**Issue by rparrett** [taurr/bevy-template-rs#20]
With the intention of creating a standalone game using the bevy engine, I ran `cargo generate taurr/bevy-template-rs --name tbev2`.

I was asked

```
⚠️   Favorite `taurr/bevy-template-rs` not found in config, using it as a git repository: https://github.com/taurr/bevy-template-rs.git
? 🤷   Which sub-template should be expanded? ›
❯ Crate
  Workflow
```

I really had no idea what to do here. I'm building a game / binary, not something that I intend to publish as a crate. I do want github workflows though, so I selected "Workflow"

But this just created a `.github` directory right in my `~/src` directory.

I then selected "Crate" instead and got what seems to be a game project going. However, there are `docs.rs` and `crates.io` links in the generated `README.md` which don't seem appropriate for a non-library.

So I'm just pretty confused by all of this.

**Comment by taurr** [comment]
@rparrett could you please try out

```shell
cargo generate taurr/bevy-template-rs --branch "taurr/issue_#20_Confusing-crate/workflow-option-on-initial-generation"
```

I hope it fixes some of the confusion - if so, I'll merge the changes, just want to check in first.

**Comment by rparrett** [comment]
Yes, that seems much better. I would have some feedback about the binary and library templates, but that can happen elsewhere/later. Maybe I'd even give `App / Library / Workflow` a think, but it's much clearer what's going on now.

I wasn't confused by the
```
⚠️   Favorite `taurr/bevy-template-rs` not found in config, using it as a git repository: https://github.com/taurr/bevy-template-rs.git
```
That seemed to make sense, even as a first-time `cargo generate` user.

The entire `Workflow` situation feels strange to me and that functionality doesn't seem worth the pain/confusion, but it's now pretty obviously not the thing to choose, so that's fine.
